In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
x = iris.data[:100]
y = iris.target[:100]
y = y.reshape([len(y) , 1])

<h3>SVM Classifier</h3>

In [3]:
class svc:
    def __init__(self , C = 0.01 , n_iters = 100 , learning_rate = 0.1):
 
        self.c = C
        self.iter = n_iters
        self.eta = learning_rate
            
    def fit(self , x , y):
        self.x = x
        self.y = y
        
        w = np.zeros([1 , x.shape[1]])
        b = 0
        
        costs = np.zeros(self.iter)
        for i in range(self.iter):
            cost = x @ w.T + b
            b = b - self.eta * self.c * sum(cost - y) 
            w = w - self.eta * self.c * sum((cost - y)*x) 
            costs[i] = self.c * sum( (y * cost)  + (1 - y)*cost ) + (1/2)* sum(w.T**2)
        
        self.w = w
        self.b = b 
        self.costs = costs
        
    
    def predict(self , x_test):
        pred_y =  []
        svc = x_test @ self.w.T + self.b
        for i in svc:
            if i >= 0:
                pred_y.append(1)
            else:
                pred_y.append(0)
        
        return pred_y

In [4]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

In [5]:
algo = svc(learning_rate=0.001 , C = 0.01)
algo.fit(x , y)

In [6]:
pred_y = algo.predict(x)

In [7]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y , pred_y))

[[50  0]
 [ 0 50]]


In [8]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , 
                                                      test_size = 0.3,
                                                      random_state = 10)

In [9]:
algo = svc(learning_rate = 0.001 , C = 0.01)
algo.fit(x_train , y_train)
y_ = algo.predict(x_train)
print(confusion_matrix(y_train , y_ ))

[[36  0]
 [ 0 34]]


In [10]:
y_hat = algo.predict(x_test)
print(confusion_matrix(y_test , y_hat))

[[14  0]
 [ 0 16]]
